// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The page order comes from the front matter in each file.
 * `docs/reference/_category_.json` turns the reference folder into a category.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
